# Where to put extra symbols:
# 0xE000-0xF8FF: 6,400 symbols
# 0xF0000-0xFFFFD: 65,534 symbols
# 0x100000-U+10FFFD: 65,534 symbols
private_range = [0xE000, 0xF8FF]

# Fonts to merge
[fonts.mikodacs]
# Name of the font (does not really matter)
name = "Micodacs"
# Path to the font file (relative to ./fonts)
filename = "Mikodacs.otf"
# Path to the file with symbols that you want to use with this font (relative to ./fonts)
symbols = "symbols.txt"
extra = [
  0x301,
]

[fonts.pretendard]
name = "Pretendard"
filename = "Pretendard-Regular.otf"
symbols = "symbols.txt"
extra = [
  0x301,
]

[fonts.bebas]
name = "Bebas Neue"
filename = "BebasNeue-Bold.otf"
symbols = "symbols.txt"
extra = [
  0x301,
]

[fonts.caveat]
name = "Caveat"
filename = "CAVEAT-VF-Regular.ttf"
symbols = "symbols.txt"
extra = [
  0x301,
]

[fonts.excelsior]
name = "Excelsior Sans"
filename = "EXCELSIORSANS-REGULAR_0 1.ttf"
symbols = "symbols.txt"
extra = [
  0x301,
]

[targets.title]
filename = "Title.ttf"
source = "Mikodacs.otf"

[targets.context]
filename = "Context.ttf"
source = "Pretendard-Regular.otf"
